# 專案名稱
name = "my-nextjs-app"

# 相容性日期
compatibility_date = "2024-11-01"

# Pages 建置輸出目錄
pages_build_output_dir = ".vercel/output/static"


# 啟用 Node.js 相容性 (如果需要)
compatibility_flags = ["nodejs_compat"]